# pytorch tensor学习

In [3]:
import numpy as np
import torch
from torch.autograd import variable
from matplotlib import pyplot as plt

## 创建tensor
### 直接创建

In [17]:
a=torch.empty(2,3) #与torch.Tensor(2,3)相同，创建一个2x3的未初始化张量
b=torch.zeros(2,3) #创建一个全部为0的2x3的张量
c=torch.ones(2,3) #创建一个全部为1的2x3的张量
d=torch.eye(2,3) #创建一个对角为1的张量
e=torch.full((2,3),4) #创建一个全部为指定数字的张量
print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d)
print("e:",e)
#以下方式也可以
#shape=(2,3,)
#torch.empty(shape)
#torch.ones(shape) #创建一个大小为shape的张量

a: tensor([[1., 1., 1.],
        [1., 1., 1.]])
b: tensor([[0., 0., 0.],
        [0., 0., 0.]])
c: tensor([[1., 1., 1.],
        [1., 1., 1.]])
d: tensor([[1., 0., 0.],
        [0., 1., 0.]])
e: tensor([[4, 4, 4],
        [4, 4, 4]])


tensor([[0.1096, 0.8125, 0.9858],
        [0.3045, 0.7077, 0.9974]])

### 从list或者numpy创建

In [15]:
a=torch.tensor([1,2,3]) #用列表数据新建tesor
tmp=np.array([2,2])
b=torch.from_numpy(tmp) #用numpy数组创建tensor,新建tensor和numpy数组公用数据
print("a:",a)
print("b:",b)
tmp[:]=[3,3]
print("b:",b) #如果tmp[:]=[1,2,3]则会报错

a: tensor([1, 2, 3])
b: tensor([2, 2], dtype=torch.int32)
b: tensor([3, 3], dtype=torch.int32)


### tensor的属性

In [19]:
a=torch.ones(2,3)
print(a.size()) #张量的大小
print(d.shape) #张量的大小
print(d.dtype) #数据类型
print(d.device) #设备，设备通常为cpu或gpu(cuda)，指tensor运行的设备

torch.Size([2, 3])
torch.Size([2, 3])
torch.float32
cpu


所有创建tensor的函数都可以指定dtype,device

In [27]:
torch.zeros(2,3,dtype=torch.long)
torch.ones(2,2,dtype=torch.float64,device='cpu')

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

### 根据范围和间距创建tesor

In [32]:
a=torch.arange(0,5,1) #[0,5)步长为1 (troch.range方法相似，表示[0,5]，但已经被废弃)
b=torch.linspace(0,5,6) #[0,5]分成6步
c=torch.logspace(0,3,4,base=10.0) #base的0次方到3次方，分成4步
print("a:",a)
print("b:",b)
print("c:",c)

a: tensor([0, 1, 2, 3, 4])
b: tensor([0., 1., 2., 3., 4., 5.])
c: tensor([   1.,   10.,  100., 1000.])


### 随机数创建tesor

In [123]:
a=torch.rand(2,2) #[0,1)均匀分布
b=torch.randint(0,5,(2,3)) #[1,5)整数均匀分布
#b=torch.randint(5,(2,2)) #[0,5)
c=torch.randperm(10) #[0,10)整数随机分布（官方未说什么分布）
d=torch.randn(2,2) #标准正态分布（均值/期望为0，标准差为1）
print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d,"  d.mean:",d.mean(),"  d.std:",d.std())

a: tensor([[0.5884, 0.7072],
        [0.6176, 0.9820]])
b: tensor([[0, 4, 1],
        [2, 1, 3]])
c: tensor([1, 6, 9, 2, 5, 0, 7, 3, 4, 8])
d: tensor([[-0.4113, -0.1502],
        [-0.4428, -1.0307]])   d.mean: tensor(-0.5087)   d.std: tensor(0.3718)


**正态分布采样**

In [166]:
a=torch.normal(10,1,(10,))#正态分布,均值为10，标准差为1）
print("standard normal dist:",a)

m=torch.arange(0,10.0,1)
s=torch.zeros(10)
b=torch.normal(m,s) #正态分布采样，每个元素时对应mean参数数值和std参数数值建立的正态分布的一个采样。
print("b:",b)

standard normal dist: tensor([ 7.4819,  9.9577,  9.0413, 10.2628,  9.0897,  8.8479, 10.6109, 11.7441,
         9.6896,  9.6596])
b: tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


**伯努利分布**

In [112]:
a=torch.bernoulli(torch.arange(0,1,0.1)) # 以参数中每个数作为概率（参数张量的值必须是0~1），生成1或0，组成一个张量，即伯努利分布
print("a:",a)

a: tensor([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])


### 根据已有tensor创建(形状与已有tensor无关)

> 所有tesor在新地址创建

In [5]:
tmp=torch.tensor([1,1])
a=tmp.new_tensor([2,2,2])#返回的tensor具有与tmp相同的torch.dtype和torch.device(cpu/gpu)
b=tmp.new_empty(2,2)
c=tmp.new_zeros(2,2)
d=tmp.new_ones(2,2)
e=tmp.new_full((2,2),4)
print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d)
print("e:",e)

a: tensor([2, 2, 2])
b: tensor([[32370111954616435, 29555306353393756],
        [31525678432190556, 27303570963497028]])
c: tensor([[0, 0],
        [0, 0]])
d: tensor([[1, 1],
        [1, 1]])
e: tensor([[4, 4],
        [4, 4]])


### 根据已有tensor创建(形状与已有tensor相同)

In [125]:
tmp=torch.tensor([[1,1],[2,2]])
a=torch.empty_like(tmp) #形状，数据类型，设备和tmp一样
b=torch.zeros_like(tmp)
c=torch.ones_like(tmp)
d=torch.full_like(tmp,4)
tmp=torch.tensor([0.0,1.0,2]) #rand不能创建int，long数据类型，所以tmp为整数类型时，rank_like会报错
e=torch.rand_like(tmp)
f=torch.randint_like(tmp,0,5)
g=torch.randn_like(tmp)
print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d)
print("e:",e)
print("f:",f)
print("g:",g)

a: tensor([[3975944217153776948, 3774971281367589986],
        [7162263158364845876, 8462385098680267893]])
b: tensor([[0, 0],
        [0, 0]])
c: tensor([[1, 1],
        [1, 1]])
d: tensor([[4, 4],
        [4, 4]])
e: tensor([0.1693, 0.6515, 0.3699])
f: tensor([2., 0., 3.])
g: tensor([-0.4190, -0.5762,  1.1849])


---

# tensor操作
## 算术运算

In [151]:
x=torch.tensor([1.,2.,3.,4.])
y=torch.ones(4)
b=x+y # 对应元素相加
print("b=x+y:",b)
c=torch.add(x,y) #同b=x+y
print("c=torch.add(x,y):",c)
d=x.add(y) #x内容不变，同d=x+y
print("c=b.add(a):",c)
x+=y  # x,y相加结果,替换b的内容
print("x:",x)
x.add_(y) #同x+=y

b=x+y: tensor([2., 3., 4., 5.])
c=torch.add(x,y): tensor([2., 3., 4., 5.])
c=b.add(a): tensor([2., 3., 4., 5.])
x: tensor([2., 3., 4., 5.])


tensor([3., 4., 5., 6.])

In [159]:
x=torch.tensor([1.,2.,3.,4.])
# 张量与数字运算时，每个元素与数字运算
a=x+1
print("a:",a)
# 张量与张量运算时，逐个元素对应运算
b=x-x
c=x/x
d=x*x
print("b:",b)
print("c:",c)
print("d:",d)
b1=x-2
c1=x/2
d1=x*2
print("b1:",b1)
print("c1:",c1)
print("d1:",d1)
b2=x.sub(x)
c2=x.mul(x)
d2=x.div(x)
print("b2:",b2)
print("c2:",c2)
print("d2:",d2)

a: tensor([2., 3., 4., 5.])
b: tensor([0., 0., 0., 0.])
c: tensor([1., 1., 1., 1.])
d: tensor([ 1.,  4.,  9., 16.])
b1: tensor([-1.,  0.,  1.,  2.])
c1: tensor([0.5000, 1.0000, 1.5000, 2.0000])
d1: tensor([2., 4., 6., 8.])
b2: tensor([0., 0., 0., 0.])
c2: tensor([ 1.,  4.,  9., 16.])
d2: tensor([1., 1., 1., 1.])


## 切片

可以使用类似Numpy的切片操作来访问tensor的一部分。
切片与原数据共享内存

In [180]:
x=torch.empty(2,4)
x[0]=torch.ones(4)
x[1]=torch.arange(0,4,1)
print("x:",x)
print("第一行：",x[0,:])
print("第一列：",x[:,0])
x[:,0]=torch.tensor([5,5])
print("修改第一列后：",x)
x[0,2:]*=2
print("第一行修改后两个：",x[0,:])
print("获取第二行的偶数位置：",x[1,0:4:2])

x: tensor([[1., 1., 1., 1.],
        [0., 1., 2., 3.]])
第一行： tensor([1., 1., 1., 1.])
第一列： tensor([1., 0.])
修改第一列后： tensor([[5., 1., 1., 1.],
        [5., 1., 2., 3.]])
第一行修改后两个： tensor([5., 1., 2., 2.])
获取第二行的偶数位置： tensor([5., 2.])


In [191]:
x=torch.arange(10,0,-1)
print("x:",x)
a=torch.index_select(x,0,torch.tensor([0,2,4])) #在x中，选择第0维，最后一个参数中位置的值
print("a:",a)
b=torch.masked_select(x,x>5) #选择指定条件的值
print("b:",b)
c=torch.nonzero(x) #选择非零元素的下标
print("c:",c)
d=torch.gather(x,0,torch.tensor([0,2,4])) #同index_select?
print("d:",d)

x: tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])
a: tensor([10,  8,  6])
b: tensor([10,  9,  8,  7,  6])
c: tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
d: tensor([10,  8,  6])


## 改变形状

用view()可以得到一个tensor改变形状后的引用,view()返回的tensor与原tensor共享内存数据

In [8]:
x=torch.arange(0,12,1)
a=x.view(3,4)
print("a:",a)
b=x.view(-1,6) #-1所指的维度会自动根据其他维度计算出来
print("b:",b)

a: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
b: tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


如果想返回不共享内存的新的tensor，使用clone创造一个副本，然后再使用view。

In [9]:
c=x.clone().view(4,-1)
print("c:",c)

c: tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


tensor使用reshape命令通常和view效果相同，但是在有些情况下会创造个副本再返回view，所以不推荐使用

In [16]:
#只有一个元素的tensor可以通过item函数得到python number
x=torch.tensor([1])
y=x.item()
print("x:",x,"y:",y)

x: tensor([1]) y: 1


### 线性代数运算

In [20]:
x=torch.arange(0,12,1).view(3,4)
print("x:",x)
print("x.trace:",x.trace()) #矩阵的迹，对角元素之和
print("")

x: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
x.trace: tensor(15)
